#!/bin/bash
# FVWM Session Save Script
# Saves window positions, sizes, and states to a file

SESSION_FILE="${1:-$HOME/.fvwm/session}"
SESSION_DIR="$(dirname "$SESSION_FILE")"

# Create session directory if it doesn't exist
mkdir -p "$SESSION_DIR"

# Clear existing session file
> "$SESSION_FILE"

# Add header
cat >> "$SESSION_FILE" << 'EOF'
# FVWM Session File
# Auto-generated by fvwm-save-session.sh
# This file contains commands to restore window positions and states

EOF

# Check if wmctrl is available
if command -v wmctrl &> /dev/null; then
    # Use wmctrl to get window information
    wmctrl -lGp | while read -r win_id desktop pid x y w h host title; do
        # Skip special windows
        if [ "$title" = "FvwmPager" ] || [ "$title" = "tint2" ] || [ "$title" = "conky" ]; then
            continue
        fi
        
        # Get window class/resource
        class=$(xprop -id "$win_id" WM_CLASS 2>/dev/null | sed 's/.*"\(.*\)", "\(.*\)".*/\2/' | head -1)
        [ -z "$class" ] && class="$title"
        
        # Get window state
        state=$(xprop -id "$win_id" _NET_WM_STATE 2>/dev/null)
        
        # Check if maximized
        maximized=""
        if echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_VERT"; then
            if echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_HORZ"; then
                maximized="100 100"
            else
                maximized="0 100"
            fi
        elif echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_HORZ"; then
            maximized="100 0"
        fi
        
        # Check if iconified
        iconified=""
        if echo "$state" | grep -q "_NET_WM_STATE_HIDDEN"; then
            iconified="Iconify"
        fi
        
        # Check if sticky
        sticky=""
        if echo "$state" | grep -q "_NET_WM_STATE_STICKY"; then
            sticky="Stick"
        fi
        
        # Write restore commands
        echo "# Window: $title" >> "$SESSION_FILE"
        echo "Next ($class, CurrentDesk) ResizeMove ${w}p ${h}p ${x}p ${y}p" >> "$SESSION_FILE"
        
        if [ -n "$maximized" ]; then
            echo "Next ($class, CurrentDesk) Maximize $maximized" >> "$SESSION_FILE"
        fi
        
        if [ -n "$iconified" ]; then
            echo "Next ($class, CurrentDesk) Iconify" >> "$SESSION_FILE"
        fi
        
        if [ -n "$sticky" ]; then
            echo "Next ($class, CurrentDesk) Stick" >> "$SESSION_FILE"
        fi
        
        if [ "$desktop" != "-1" ] && [ "$desktop" != "0" ]; then
            echo "Next ($class, CurrentDesk) MoveToDesk 0 $desktop" >> "$SESSION_FILE"
        fi
        
        echo "" >> "$SESSION_FILE"
    done
else
    # Fallback using xwininfo and xprop
    # Get all window IDs
    window_ids=$(xprop -root _NET_CLIENT_LIST 2>/dev/null | sed 's/.*# //; s/,//g')
    
    for win_id in $window_ids; do
        # Get window info
        win_info=$(xwininfo -id "$win_id" 2>/dev/null)
        [ -z "$win_info" ] && continue
        
        # Extract geometry
        x=$(echo "$win_info" | grep "Absolute upper-left X:" | awk '{print $4}')
        y=$(echo "$win_info" | grep "Absolute upper-left Y:" | awk '{print $4}')
        w=$(echo "$win_info" | grep "Width:" | head -1 | awk '{print $2}')
        h=$(echo "$win_info" | grep "Height:" | head -1 | awk '{print $2}')
        
        # Get window class
        class=$(xprop -id "$win_id" WM_CLASS 2>/dev/null | sed 's/.*"\(.*\)", "\(.*\)".*/\2/' | head -1)
        title=$(xprop -id "$win_id" WM_NAME 2>/dev/null | sed 's/.*= "\(.*\)".*/\1/')
        
        [ -z "$class" ] && class="$title"
        
        # Skip special windows
        if [ "$class" = "FvwmPager" ] || [ "$class" = "tint2" ] || [ "$class" = "conky" ]; then
            continue
        fi
        
        # Get window state
        state=$(xprop -id "$win_id" _NET_WM_STATE 2>/dev/null)
        
        # Check states
        maximized=""
        if echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_VERT"; then
            if echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_HORZ"; then
                maximized="100 100"
            else
                maximized="0 100"
            fi
        elif echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_HORZ"; then
            maximized="100 0"
        fi
        
        iconified=""
        if echo "$state" | grep -q "_NET_WM_STATE_HIDDEN"; then
            iconified="Iconify"
        fi
        
        sticky=""
        if echo "$state" | grep -q "_NET_WM_STATE_STICKY"; then
            sticky="Stick"
        fi
        
        # Write restore commands
        echo "# Window: $title" >> "$SESSION_FILE"
        echo "Next ($class, CurrentDesk) ResizeMove ${w}p ${h}p ${x}p ${y}p" >> "$SESSION_FILE"
        
        if [ -n "$maximized" ]; then
            echo "Next ($class, CurrentDesk) Maximize $maximized" >> "$SESSION_FILE"
        fi
        
        if [ -n "$iconified" ]; then
            echo "Next ($class, CurrentDesk) Iconify" >> "$SESSION_FILE"
        fi
        
        if [ -n "$sticky" ]; then
            echo "Next ($class, CurrentDesk) Stick" >> "$SESSION_FILE"
        fi
        
        echo "" >> "$SESSION_FILE"
    done
fi

echo "Session saved to: $SESSION_FILE"
echo "Saved $(grep -c "^# Window:" "$SESSION_FILE" 2>/dev/null || echo 0) windows"
