#!/bin/bash
# FVWM Session Save Script
# Saves window positions, sizes, states, and application launch commands

SESSION_FILE="${1:-$HOME/.fvwm/session}"
SESSION_DIR="$(dirname "$SESSION_FILE")"
APP_LIST_FILE="${SESSION_DIR}/session-apps"

# Create session directory if it doesn't exist
mkdir -p "$SESSION_DIR"

# Clear existing session files
> "$SESSION_FILE"
> "$APP_LIST_FILE"

# Add header to session file
cat >> "$SESSION_FILE" << 'EOF'
# FVWM Session File
# Auto-generated by fvwm-save-session.sh
# This file contains commands to restore window positions and states

EOF

# Add header to app list file
cat >> "$APP_LIST_FILE" << 'EOF'
# FVWM Session Application List
# Auto-generated by fvwm-save-session.sh
# This file contains application commands to restore running applications

EOF

# Track saved applications to avoid duplicates
declare -A saved_apps

# Get screen dimensions to calculate page
SCREEN_WIDTH=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d'x' -f1)
SCREEN_HEIGHT=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d'x' -f2)

# Check if wmctrl is available
if command -v wmctrl &> /dev/null; then
    # Use wmctrl to get window information
    wmctrl -lGp | while read -r win_id desktop pid x y w h host title; do
        # Skip special windows
        if [ "$title" = "FvwmPager" ] || [ "$title" = "tint2" ] || [ "$title" = "conky" ]; then
            continue
        fi
        
        # Get window class/resource
        class=$(xprop -id "$win_id" WM_CLASS 2>/dev/null | sed 's/.*"\(.*\)", "\(.*\)".*/\2/' | head -1)
        [ -z "$class" ] && class="$title"
        
        # Calculate page from window position
        # Page X = window_x / screen_width
        # Page Y = window_y / screen_height
        page_x=0
        page_y=0
        if [ -n "$SCREEN_WIDTH" ] && [ "$SCREEN_WIDTH" -gt 0 ]; then
            page_x=$((x / SCREEN_WIDTH))
        fi
        if [ -n "$SCREEN_HEIGHT" ] && [ "$SCREEN_HEIGHT" -gt 0 ]; then
            page_y=$((y / SCREEN_HEIGHT))
        fi
        
        # Get the command that started this application
        if [ -n "$pid" ] && [ "$pid" != "0" ]; then
            # Try to get the command line
            cmdline=""
            if [ -f "/proc/$pid/cmdline" ]; then
                cmdline=$(tr '\0' ' ' < "/proc/$pid/cmdline" | sed 's/ $//')
            fi
            
            # If we have a valid command and haven't saved this app yet, save it
            if [ -n "$cmdline" ] && [ -z "${saved_apps[$class]}" ]; then
                echo "# Application: $class (PID: $pid)" >> "$APP_LIST_FILE"
                echo "APP_CLASS=\"$class\"" >> "$APP_LIST_FILE"
                echo "APP_DESKTOP=\"$desktop\"" >> "$APP_LIST_FILE"
                echo "APP_PAGE_X=\"$page_x\"" >> "$APP_LIST_FILE"
                echo "APP_PAGE_Y=\"$page_y\"" >> "$APP_LIST_FILE"
                echo "APP_CMD=\"$cmdline\"" >> "$APP_LIST_FILE"
                echo "" >> "$APP_LIST_FILE"
                saved_apps[$class]=1
            fi
        fi
        
        # Get window state
        state=$(xprop -id "$win_id" _NET_WM_STATE 2>/dev/null)
        
        # Check if maximized
        maximized=""
        if echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_VERT"; then
            if echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_HORZ"; then
                maximized="100 100"
            else
                maximized="0 100"
            fi
        elif echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_HORZ"; then
            maximized="100 0"
        fi
        
        # Check if iconified
        iconified=""
        if echo "$state" | grep -q "_NET_WM_STATE_HIDDEN"; then
            iconified="Iconify"
        fi
        
        # Check if sticky
        sticky=""
        if echo "$state" | grep -q "_NET_WM_STATE_STICKY"; then
            sticky="Stick"
        fi
        
        # Calculate position relative to page
        # When restoring, window should be positioned relative to its page
        pos_x=$((x % SCREEN_WIDTH))
        pos_y=$((y % SCREEN_HEIGHT))
        
        # Write restore commands
        echo "# Window: $title (Class: $class, Desktop: $desktop, Page: ${page_x},${page_y})" >> "$SESSION_FILE"
        
        # Move to correct desktop and page first
        if [ "$desktop" != "-1" ]; then
            echo "Next ($class) GotoDesk 0 $desktop" >> "$SESSION_FILE"
            echo "Next ($class) GotoPage $page_x $page_y" >> "$SESSION_FILE"
        fi
        
        # Now position the window
        echo "Next ($class) ResizeMove ${w}p ${h}p ${pos_x}p ${pos_y}p" >> "$SESSION_FILE"
        
        if [ -n "$maximized" ]; then
            echo "Next ($class) Maximize $maximized" >> "$SESSION_FILE"
        fi
        
        if [ -n "$iconified" ]; then
            echo "Next ($class) Iconify" >> "$SESSION_FILE"
        fi
        
        if [ -n "$sticky" ]; then
            echo "Next ($class) Stick" >> "$SESSION_FILE"
        fi
        
        echo "" >> "$SESSION_FILE"
    done
else
    # Fallback using xwininfo and xprop
    # Get all window IDs
    window_ids=$(xprop -root _NET_CLIENT_LIST 2>/dev/null | sed 's/.*# //; s/,//g')
    
    for win_id in $window_ids; do
        # Get window info
        win_info=$(xwininfo -id "$win_id" 2>/dev/null)
        [ -z "$win_info" ] && continue
        
        # Extract geometry
        x=$(echo "$win_info" | grep "Absolute upper-left X:" | awk '{print $4}')
        y=$(echo "$win_info" | grep "Absolute upper-left Y:" | awk '{print $4}')
        w=$(echo "$win_info" | grep "Width:" | head -1 | awk '{print $2}')
        h=$(echo "$win_info" | grep "Height:" | head -1 | awk '{print $2}')
        
        # Get window class
        class=$(xprop -id "$win_id" WM_CLASS 2>/dev/null | sed 's/.*"\(.*\)", "\(.*\)".*/\2/' | head -1)
        title=$(xprop -id "$win_id" WM_NAME 2>/dev/null | sed 's/.*= "\(.*\)".*/\1/')
        
        [ -z "$class" ] && class="$title"
        
        # Skip special windows
        if [ "$class" = "FvwmPager" ] || [ "$class" = "tint2" ] || [ "$class" = "conky" ]; then
            continue
        fi
        
        # Get desktop number
        desktop=$(xprop -id "$win_id" _NET_WM_DESKTOP 2>/dev/null | awk '{print $3}')
        [ -z "$desktop" ] && desktop="0"
        
        # Calculate page from window position
        page_x=0
        page_y=0
        if [ -n "$SCREEN_WIDTH" ] && [ "$SCREEN_WIDTH" -gt 0 ]; then
            page_x=$((x / SCREEN_WIDTH))
        fi
        if [ -n "$SCREEN_HEIGHT" ] && [ "$SCREEN_HEIGHT" -gt 0 ]; then
            page_y=$((y / SCREEN_HEIGHT))
        fi
        
        # Calculate position relative to page
        pos_x=$((x % SCREEN_WIDTH))
        pos_y=$((y % SCREEN_HEIGHT))
        
        # Get window state
        state=$(xprop -id "$win_id" _NET_WM_STATE 2>/dev/null)
        
        # Check states
        maximized=""
        if echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_VERT"; then
            if echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_HORZ"; then
                maximized="100 100"
            else
                maximized="0 100"
            fi
        elif echo "$state" | grep -q "_NET_WM_STATE_MAXIMIZED_HORZ"; then
            maximized="100 0"
        fi
        
        iconified=""
        if echo "$state" | grep -q "_NET_WM_STATE_HIDDEN"; then
            iconified="Iconify"
        fi
        
        sticky=""
        if echo "$state" | grep -q "_NET_WM_STATE_STICKY"; then
            sticky="Stick"
        fi
        
        # Write restore commands
        echo "# Window: $title (Class: $class, Desktop: $desktop, Page: ${page_x},${page_y})" >> "$SESSION_FILE"
        
        # Move to correct desktop and page first
        if [ "$desktop" != "-1" ]; then
            echo "Next ($class) GotoDesk 0 $desktop" >> "$SESSION_FILE"
            echo "Next ($class) GotoPage $page_x $page_y" >> "$SESSION_FILE"
        fi
        
        # Now position the window
        echo "Next ($class) ResizeMove ${w}p ${h}p ${pos_x}p ${pos_y}p" >> "$SESSION_FILE"
        
        if [ -n "$maximized" ]; then
            echo "Next ($class) Maximize $maximized" >> "$SESSION_FILE"
        fi
        
        if [ -n "$iconified" ]; then
            echo "Next ($class) Iconify" >> "$SESSION_FILE"
        fi
        
        if [ -n "$sticky" ]; then
            echo "Next ($class) Stick" >> "$SESSION_FILE"
        fi
        
        echo "" >> "$SESSION_FILE"
    done
fi

window_count=$(grep -c "^# Window:" "$SESSION_FILE" 2>/dev/null || echo 0)
app_count=$(grep -c "^APP_CLASS=" "$APP_LIST_FILE" 2>/dev/null || echo 0)

echo "Session saved to: $SESSION_FILE"
echo "Saved $window_count windows and $app_count applications"
echo "Application commands saved to: $APP_LIST_FILE"
